### ISSUE TITLE
extension error on upload

### ISSUE THREAD

**Issue by elieandraos** [freekmurze/laravel-medialibrary#1]
hi guys, 
i am trying your package as i think it is just what i need :) 
i managed to instal and configure as your docs, 
i am haing a problem uploading an image though

I am getting the following error:
ErrorException in MediaLibraryRepository.php line 165:
Undefined index: extension

in you repos, pathinfo() doesn't return the extension. 
i am calling the addMedia with my model and not the facade.

$file = Input::file('image');
$collectionName = $news->getMediaCollectionName(); //method i created in my model
$news->addMedia($file, $collectionName);

**Comment by elieandraos** [comment]
just as a test, i set the extension to 'jpg' hard coded in your repos createMediaForFile() function.
the file is uploaded and a record is saved to the media table with no errors, but the file uploaded is the tmp file (phpPPGBy5 for example), and not the original client name with the extension, and i think by that, the image profiles are not taken into place. 

i think i am missing something here...

**Comment by freekmurze** [comment]
Hi,

you should pass a properly named file to the addMedia-method. To get the filename of the uploaded file (and not the tempfile) you can do something like this:

```php
$file = Input::file('file');

$tempDirectory = storage_path('temp');
$fileName = $file->getClientOriginalName();

$file->move($tempDirectory, $fileName);

$collectionName = $news->getMediaCollectionName();
$news->addMedia($tempDirectory . '/' . $fileName, $collectionName);
```

**Comment by elieandraos** [comment]
Works perfectly well 
Many thanks :)

**Comment by groenewege** [comment]
Hello,

Thank you for this great package !

I struggled with the same issue.
Maybe you should put this example in the README file.

**Comment by rashid-ali4u** [comment]
Hi , 
I am getting following error. 
Call to undefined method Illuminate\Database\Query\Builder::addMedia()

**Comment by freekmurze** [comment]
@rashid-ali4u did you [prepare your model](http://medialibrary.spatie.be/v3/basic-usage/preparing-your-model/) correctly?
