### ISSUE TITLE
Profile sizes

### ISSUE THREAD

**Issue by rawcreative** [freekmurze/laravel-medialibrary#2]
In the Readme it says the `getImageProfileProperties` method can be placed on the Model to define profiles that will be created for each image associated with the model. Defining this however doesn't seem to do anything, and I can't find any calls to that method in the codebase. Am I missing something or is this just not implemented?

**Comment by rawcreative** [comment]
Digging a little deeper it appears the `GlideImageManipulator:: getModelImageProfiles()` method, looks for the `imageProfiles` attribute on the model. So changing `getImageProfileProperties` to `getImageProfilesAttribute` returns the profiles properly, however it only appears to create one profile image unless shouldBeQueued is set to false. I've tried with both the sync queue driver and beanstalk, and it seems only the first profile is being queued.

**Comment by freekmurze** [comment]
I've taken a look at the code and there are indeed some problems with the image profile properties. I'll fix them somewhere this week.

**Comment by freekmurze** [comment]
The problems you described have been fixed in version 1.1.4
