### ISSUE TITLE
Adding PNG Type

### ISSUE THREAD

**Issue by codybutz** [freekmurze/laravel-medialibrary#4]
Hey,

I am requesting you allow the use of PNG Image Type, it would be very useful.

Thanks,

Cody

**Comment by freekmurze** [comment]
Png's are supported. Could you please clarify your question? Are you getting an error?

**Comment by codybutz** [comment]
When I upload png's they are formatted to jpgs. Is there a flag I am missing to make sure it doesn't automatically save it out as a jpg?

**Comment by freekmurze** [comment]
I've made it a bit more clear in the readme that you can use Glide's fm-option.

By default the derived images will be stored as `jpg`'s. If you want another image format you can specify `png`or `gif` using the `fm`-key in an an imageprofile. For example:
```php
//in your news model
public static function getImageProfileProperties()
{
    return [
        'list'=> ['w'=>200, 'h'=>200, 'shouldBeQueued' => false, 'fm' => 'png'],
        'detail'=> ['w'=>1600, 'h'=>800, 'shouldBeQueued' => false, 'fm' => 'png'],
    ];
}
```
